
export const SEARCH_MOVIE = 'SEARCH_MOVIE';


export const LIST_MOVIES_REQUEST = 'LIST_MOVIES_REQUEST';
export const LIST_MOVIES_SUCCESS = 'LIST_MOVIES_SUCCESS';
export const LIST_MOVIES_FAILURE = 'LIST_MOVIES_FAILURE';

export const DETAIL_MOVIE = 'DETAIL_MOVIE';
export const LOADING = 'LOADING';